services:
  - type: web
    name: wagtail-app
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn my_project.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DJANGO_SETTINGS_MODULE
        value: my_project.settings.production
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4

databases:
  - name: wagtail-db
    databaseName: wagtail
    user: wagtail
